export const CANONICAL_SCHEMA_VERSION = 1 as const;

export * from "./enums.js";
export * from "./primitives.js";
export * from "./mechanics.js";
export * from "./feature-rules.js";
export * from "./class-mechanics.js";
export * from "./class-rules.js";
export * from "./wizard-mechanics.js";
export * from "./activity.js";
export * from "./monster-feature.js";
export * from "./monster.js";
export * from "./vehicle.js";
export * from "./item.js";
export * from "./inventory.js";
export * from "./spell.js";
export * from "./feature.js";
export * from "./progression.js";
export * from "./content.js";
export * from "./validation.js";
export * from "./migration.js";
export * from "./compatibility-fixtures.js";
