import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import test from 'node:test';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
function loadNormalizer(file,exportName){const source=read(file),store=new Map;const context={console,structuredClone,JSON,Date,Map,Set,RegExp,String,Number,Array,Object,Math,CustomEvent:class{},setTimeout:()=>0,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},window:{addEventListener(){},dispatchEvent(){}}};vm.createContext(context);new vm.Script(source).runInContext(context);return context.window[exportName]}

test('compendium category strip supports wheel, pointer drag and arrows',()=>{const js=read('public/compendium-category-nav.js'),css=read('public/compendium-category-nav.css');assert.match(js,/scrollBy/);assert.match(js,/wheel/);assert.match(js,/pointerdown/);assert.match(css,/category-nav-arrow/);assert.match(css,/overflow/)});

test('campaign cards expose account-backed delete action',()=>{const source=read('public/home-campaign-account-sync.js');assert.match(source,/data-delete-campaign/);assert.match(source,/OracleAccountData\?\.removeCampaign/);assert.match(source,/Esta ação não pode ser desfeita/)});

test('Blood Hunter-like class import becomes level progression and class features',()=>{const normalizer=loadNormalizer('public/homebrew-class-normalizer.js','OracleClassHomebrewNormalizer');const rules=`Blood Hunter\nHit Die: d8\nPrimary Ability: Intelligence\nSaving Throws: Dexterity, Intelligence\nArmor: Light armor, medium armor\nWeapons: Simple weapons, martial weapons\nSkills: Choose 2 from Acrobatics, Arcana, Investigation, Survival\n\n| Level | Proficiency Bonus | Features | Hemocraft Die | Blood Curses Known |\n| --- | --- | --- | --- | --- |\n| 1st | +2 | Hemocraft, Weapon Mastery | d6 | 2 |\n| 2nd | +2 | Crimson Rite | d6 | 2 |\n| 3rd | +2 | Blood Hunter Order | d6 | 2 |\n\nLevel 1: Hemocraft\nYou have a hemocraft die, which is a d6.\n\nLevel 1: Weapon Mastery\nYou can use the mastery properties of two weapons.\n\nLevel 2: Crimson Rite\nYou can invoke a rite on a weapon.`;const cls={id:'homebrew:blood-hunter',canonicalId:'homebrew:blood-hunter',category:'classes',name:'Blood Hunter',entity:{id:'homebrew:blood-hunter',canonicalId:'homebrew:blood-hunter',entityType:'class',name:'Blood Hunter',data:{text:{summary:'Blood Hunter',rules:[rules]},advancement:[],primaryAbilities:[],savingThrowProficiencies:[],armorTraining:[],weaponProficiencies:[],skillChoices:{count:2,options:[]}}}};const lib=[cls],next=normalizer.normalizeLibrary(lib);assert.ok(next);const features=lib.filter(x=>x.category==='class-features');assert.equal(features.length,4);assert.deepEqual(Array.from(cls.entity.data.primaryAbilities),['int']);assert.deepEqual(Array.from(cls.entity.data.savingThrowProficiencies),['dex','int']);assert.equal(cls.entity.data.advancement.length,3);assert.equal(cls.entity.data.advancement[0].grants.length,2);assert.equal(cls.entity.data.advancement[1].grants[0].entity.name,'Crimson Rite');assert.equal(cls.entity.data.advancement[0].scaleValues['hemocraft-die'],'d6');assert.equal(cls.entity.data.advancement[0].scaleValues['blood-curses-known'],'2')});

test('Cambion-like species import creates trait features and level-based spell grants',()=>{const normalizer=loadNormalizer('public/homebrew-species-normalizer.js','OracleSpeciesHomebrewNormalizer');const rules=`Cambion Traits\n\nDarkvision\nYou can see in dim light within 60 feet.\n\nFiendish Resistance\nYou have resistance to fire damage.\n\nFiendish Legacy\nYou know the Thaumaturgy cantrip. At 3rd level, you can cast the Hellish Rebuke spell once with this trait. At 5th level, you can cast the Darkness spell once with this trait. Charisma is your spellcasting ability for these spells. You regain the ability to cast them when you finish a Long Rest.`;const species={id:'homebrew:cambion',canonicalId:'homebrew:cambion',category:'species',name:'Cambion',entity:{id:'homebrew:cambion',canonicalId:'homebrew:cambion',entityType:'species',name:'Cambion',data:{size:['medium'],speed:30,features:[],text:{summary:'Cambion',rules:[rules]}}}};const lib=[species],next=normalizer.normalizeLibrary(lib);assert.ok(next);const features=lib.filter(x=>x.category==='species-features');assert.ok(features.length>=3);const legacy=features.find(x=>/Fiendish Legacy/i.test(x.name));assert.ok(legacy);const grants=legacy.entity.data.grantedSpells;assert.equal(grants.length,3);assert.deepEqual(Array.from(grants.map(x=>x.minLevel)),[1,3,5]);assert.ok(grants.every(x=>x.ability==='cha'));assert.equal(species.entity.data.spellGrants.length,1);assert.equal(species.entity.data.spellGrants[0].selections[2].characterLevel,5)});
