import { attach, createDocumentIR, createEntityIR } from './ir.mjs';
const arr=v=>Array.isArray(v)?v:v==null?[]:[v];const featureRefKey=ref=>String(ref||'').split('|').slice(0,3).join('|').toLowerCase();
function entriesText(v){return arr(v).map(x=>typeof x==='string'?x:JSON.stringify(x)).join('\n')}
export function parse5etoolsJson(payload,{sourceName='5etools-json'}={}){const ir=createDocumentIR({sourceType:'5etools-json',sourceName,raw:''});const classes=arr(payload?.class),classFeatures=arr(payload?.classFeature),subclasses=arr(payload?.subclass),subclassFeatures=arr(payload?.subclassFeature);
for(const cls of classes){const classEntity=createEntityIR({kind:'class',name:cls.name,data:{source:cls.source||'',hitDie:cls.hd?.faces||null,hitDieNumber:cls.hd?.number||1,savingThrows:arr(cls.proficiency),primaryAbility:arr(cls.primaryAbility),spellcastingAbility:cls.spellcastingAbility||null,casterProgression:cls.casterProgression||null,startingProficiencies:cls.startingProficiencies||null,startingEquipment:cls.startingEquipment||null,classTableGroups:arr(cls.classTableGroups),classFeatures:arr(cls.classFeatures)}});ir.entities.push(classEntity);const refs=new Map();arr(cls.classFeatures).forEach((entry,index)=>{const ref=typeof entry==='string'?entry:entry?.classFeature;if(ref)refs.set(featureRefKey(ref),{ref,index})});for(const feature of classFeatures){if(String(feature.className||'').toLowerCase()!==String(cls.name||'').toLowerCase())continue;const key=featureRefKey(`${feature.name}|${feature.className}|${feature.classSource||cls.source}|${feature.level}`),matched=[...refs.entries()].find(([r])=>r.startsWith(featureRefKey(`${feature.name}|${feature.className}`)));attach(classEntity,createEntityIR({kind:'classFeature',name:feature.name,parentId:cls.name,level:Number(feature.level)||null,data:{source:feature.source||feature.classSource||cls.source||'',entries:feature.entries||[],choiceOptions:arr(feature.options||feature.choose),uses:feature.uses||null,key,ref:matched?.[1]?.ref||null}}))}for(const sub of subclasses){if(String(sub.className||'').toLowerCase()!==String(cls.name||'').toLowerCase())continue;const se=createEntityIR({kind:'subclass',name:sub.name,parentId:cls.name,data:{shortName:sub.shortName||sub.name,source:sub.source||'',classSource:sub.classSource||cls.source||'',subclassFeatures:arr(sub.subclassFeatures),additionalSpells:sub.additionalSpells||null}});attach(classEntity,se);for(const feature of subclassFeatures){if(String(feature.className||'').toLowerCase()!==String(cls.name||'').toLowerCase())continue;const same=[feature.subclassShortName,feature.subclassName].filter(Boolean).some(v=>String(v).toLowerCase()===String(sub.shortName||sub.name).toLowerCase());if(same)attach(se,createEntityIR({kind:'subclassFeature',name:feature.name,parentId:sub.name,level:Number(feature.level)||null,data:{source:feature.source||sub.source||'',entries:feature.entries||[],choiceOptions:arr(feature.options||feature.choose),uses:feature.uses||null}}))}}}
const species=arr(payload?.race||payload?.species);for(const x of species)ir.entities.push(createEntityIR({kind:'species',name:x.name,data:{source:x.source,size:x.size,speed:x.speed,traits:arr(x.entries).filter(e=>e&&typeof e==='object'&&e.name).map(e=>({name:e.name,rules:[entriesText(e.entries)]})),features:arr(x.features),spellGrants:arr(x.additionalSpells||x.spellcasting),languages:x.languageProficiencies||x.languages,languageChoices:x.languageChoices}}));
for(const x of arr(payload?.background))ir.entities.push(createEntityIR({kind:'background',name:x.name,data:{source:x.source,features:arr(x.entries).filter(e=>e&&typeof e==='object'&&e.name).map(e=>({name:e.name,rules:[entriesText(e.entries)]})),skillChoices:x.skillProficiencies,languageChoices:x.languageProficiencies,toolChoices:x.toolProficiencies,startingEquipment:x.startingEquipment}}));
for(const x of arr(payload?.feat))ir.entities.push(createEntityIR({kind:'feat',name:x.name,data:{source:x.source,prerequisite:x.prerequisite,abilityChoices:x.ability,activities:x.activities,spellGrants:arr(x.additionalSpells),rules:[entriesText(x.entries)]}}));
for(const x of arr(payload?.item))ir.entities.push(createEntityIR({kind:'item',name:x.name,data:{source:x.source,itemKind:x.type,properties:x.property,attunement:x.reqAttune,charges:x.charges,recovery:x.recharge,activities:x.activities,containedItems:x.container?.items||x.contents,container:x.container,rules:[entriesText(x.entries)]}}));return ir}
