import { parse5etoolsJson } from './5etools-adapter.mjs';
import { parse5etoolsMarkdown } from './markdown-adapter.mjs';
import { hardenMarkdown } from './markdown-hardening.mjs';
import { parseBackgroundMarkdown } from './background-markdown-adapter.mjs';
import { isStandaloneSubclassMarkdown, parseStandaloneSubclassMarkdown } from './subclass-markdown-adapter.mjs';
import { isMultiSubclassDocument, parseMultiSubclassDocument } from './multi-subclass-document-adapter.mjs';
import { compileClassDocument, compileClassBundleDocument } from './class-compiler.mjs';
import { createReferenceResolver, compileSpeciesDocument, compileBackgroundDocument, compileFeatDocument, compileItemDocument } from './domain-compilers.mjs';
function adapter(source,{format='auto',sourceName='',expectedKind='class'}={}){if(format==='5etools-json'||(format==='auto'&&source&&typeof source==='object'))return parse5etoolsJson(source,{sourceName});const text=String(source||'');if(expectedKind==='background')return parseBackgroundMarkdown(text,{sourceName});if(expectedKind==='class'&&isMultiSubclassDocument(text))return parseMultiSubclassDocument(text,{sourceName});if(expectedKind==='class'&&isStandaloneSubclassMarkdown(text))return parseStandaloneSubclassMarkdown(text,{sourceName});const markdown=hardenMarkdown(text,{sourceName,expectedKind});return parse5etoolsMarkdown(markdown,{sourceName,expectedKind})}
const wrapFeat=(entity)=>({id:entity.canonicalId,canonicalId:entity.canonicalId,category:'feats',entityType:entity.entityType,name:entity.name,summary:entity.data?.text?.summary||'',entity});
const compileClasses=(ir,resolve)=>{const base=ir.entities?.filter(e=>e.kind==='class').length>1?compileClassBundleDocument(ir,{resolve}):compileClassDocument(ir,{resolve});const featNodes=ir.entities?.filter(e=>e.kind==='feat')||[];if(!featNodes.length)return base;const entries=[...base.entries],diagnostics=[...(base.diagnostics||[])];for(const root of featNodes){const compiled=compileFeatDocument({root},{resolve});entries.push(...compiled.entities.map(wrapFeat));diagnostics.push(...(compiled.unresolved||[]).map(x=>({severity:'warning',code:'UNRESOLVED_REFERENCE',...x})));}return{entries,diagnostics};};
export function importClass(source,{format='auto',sourceName='',compendium=[]}={}){const ir=adapter(source,{format,sourceName,expectedKind:'class'}),resolve=createReferenceResolver(compendium);return{ir,...compileClasses(ir,resolve)}}
export function importDocument(source,{kind,format='auto',sourceName='',compendium=[]}={}){const aliases={race:'species'},target=aliases[kind]||kind,ir=adapter(source,{format,sourceName,expectedKind:target}),resolve=createReferenceResolver(compendium);if(target==='class')return{ir,...compileClasses(ir,resolve)};const root=ir.entities?.find(e=>e.kind===target)||ir.root||ir,compiler={species:compileSpeciesDocument,background:compileBackgroundDocument,feat:compileFeatDocument,item:compileItemDocument}[target];if(!compiler)throw new Error(`Unsupported import kind: ${kind}`);return{ir,...compiler({root},{resolve})}}
export { parse5etoolsJson, parse5etoolsMarkdown, hardenMarkdown, parseBackgroundMarkdown, parseStandaloneSubclassMarkdown, isStandaloneSubclassMarkdown, parseMultiSubclassDocument, isMultiSubclassDocument, compileClassDocument, compileClassBundleDocument, createReferenceResolver, compileSpeciesDocument, compileBackgroundDocument, compileFeatDocument, compileItemDocument };
